name: 'Little Sages Books '
favicon: null
layout_spectrum: 0.51871
typography_spectrum: 0.49702
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b5a48a'
    - '#dbd7ce'
    - '#59473b'
    - '#867970'
    - '#323137'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.48650993849150836
purpose: []
