name: 'Little Sages Books '
favicon: null
layout_spectrum: 0.16591295483522117
typography_spectrum: 0.35854991525411606
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4455187062267214
  lightness: 0.6595161184668541
  saturation: 0.18488106690347195
  rhythmicContrast: 0.48650993849150836
purpose: []
